IPFS:
    Endpoint: ipfs.digscar.com:5001
Eosio:
    Endpoint: https://kylin.eosusa.news
    PublishAccount: messengerbus
    PublishPrivateKey: 5KAP1zytghuvowgprSPLNasajibZcxf4KMgdgNbrNj98xhcGAUa
Dfuse:
    WSEndpoint: wss://kylin.eos.dfuse.io/v1/stream
    Origin: github.com/eosio-enterprise/chappe
    ApiKey: <insert dfuse API key here>
KeyDirectory: channels/