IPFS:
    Endpoint: ipfs.digscar.com:5001
Eosio:
    Endpoint: https://kylin.eosusa.news
    PublishAccount: messengerbus
    PublishPrivateKey: 5KAP1zytghuvowgprSPLNasajibZcxf4KMgdgNbrNj98xhcGAUa
Dfuse:
    Protocol: GraphQL  # only GraphQL supported now
    WSEndpoint: wss://kylin.eos.dfuse.io/v1/stream # only GraphQL supported now
    Origin: github.com/eosio-enterprise/chappe
    ApiKey: <<insert dfuse api key here>>
    GraphQLEndpoint: kylin.eos.dfuse.io:443
    AuthEndpoint: https://auth.dfuse.io/v1/auth/issue
KeyDirectory: channels/
PublishInterval: 5s  # Go Duration object
DeviceRSAPrivateKey: mykey # uniquely represents the device (used for receipts)

# coming soon
RevealMessage: true
RevealDelay: 60s  # Time to wait before revealing the message